### PR TITLE
Fix building error & NSTableView swizzled issue

### PR DESCRIPTION
**Pull request by Mx-Iris**
I tried to fix the building error, and also NSTableViewDataSource should not strongly reference NSTableView.

### CODE REVIEW

**Comment by Mx-Iris** [comment]
I created a custom TableView causing swizzled to execute repeatedly, should not use `self` as the object of the associated object, should use `NSTableView.self` to ensure it only executes once!

**Comment by flocked** [comment]
Thanks! I can't replicate the error regarding swizzling. How did you swizzle your table view?

**Comment by Mx-Iris** [comment]
@flocked You need to create a custom class that inherits from `NSTableView`, then create an `NSTableView`, and use `TableViewDiffableDataSource` to reproduce the error. Since the custom TableView and `NSTableView` are different class objects, their `didSwizzle` properties are not the same.

**Comment by Mx-Iris** [comment]
[TableViewSwizzledIssue.zip](https://github.com/flocked/AdvancedCollectionTableView/files/14627275/TableViewSwizzledIssue.zip)
This is a reproduced example, because the repeated exchange method caused makeView(withIdentifier: identifier, owner: nil) to call back to Apple's original implementation, which did not create CellClass.

**Pull request closed without merging**
